In [1]:
import numpy as np

In [2]:
pylist=[1,3,4,5]
print(pylist)

[1, 3, 4, 5]


In [3]:
numpy_array_from_list=np.array(pylist)
numpy_array_from_list

array([1, 3, 4, 5])

In [4]:
b=np.array([1,3,5,2,5])
print(b)

[1 3 5 2 5]


In [6]:
x=numpy_array_from_list+100
print(x)

[101 103 104 105]


In [9]:
a=np.array([1,3,5,6])
print(a.shape)
print(a.dtype)

(4,)
int32


In [10]:
b=np.array([2.2,5.7,7.9])
b.dtype

dtype('float64')

In [18]:
c=np.array([(22,57,79),(1,3,57)])
print(c)


[[22 57 79]
 [ 1  3 57]]


In [21]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [23]:
 x=np.zeros((3,3),dtype=np.int16)
 print(x) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
 x=np.ones((4,4),dtype=np.int16)
 print(x) 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
e  = np.array([(3,4,9), (4,5,6)])
print(e)
e.reshape(3,2)

[[3 4 9]
 [4 5 6]]


array([[3, 4],
       [9, 4],
       [5, 6]])

In [27]:
e.flatten()

array([3, 4, 9, 4, 5, 6])

In [28]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [29]:
print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [30]:
normal_array = np.random.normal(10, 1, 10)
print(normal_array)

[ 9.04340118 10.58954048  8.17286596 10.54003932 10.81807121  9.92587956
  9.90164853  9.82849145  9.70873313 12.01894087]


In [31]:
A = np.matrix(np.ones((4,4)))
np.array(A)[2]=2  
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#immutable so converting into array
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [33]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [35]:
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [36]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [2]:
import numpy as np
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [3]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [4]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
print('First row:', e[0])

[[1 2 3]
 [4 5 6]]
First row: [1 2 3]


In [5]:
print('Second row:', e[1])

Second row: [4 5 6]


In [6]:
print('Second column:', e[:,1])

Second column: [2 5]


In [7]:
print(e[1, :2])

[4 5]


In [8]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.43225141 4.58327337 4.03097125 4.85205265 4.74480524 4.73462082
 4.98380309 5.20792827 5.01365045 5.6736266 ]


In [9]:
print(np.min(normal_array))
print(np.max(normal_array)) 
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

4.030971254824812
5.6736266034686835
4.825698316498784
4.7984289444134705
0.4226227650328319


In [10]:
f = np.array([1,2,6])
g = np.array([4,5,5])

np.dot(f, g)

44

In [11]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [12]:
A = np.array([[6, 1, 1],
              [4, 2, 5],
              [2, 8, 7]])
print(np.linalg.inv(A))

[[ 0.17808219 -0.00684932 -0.02054795]
 [ 0.12328767 -0.2739726   0.17808219]
 [-0.19178082  0.31506849 -0.05479452]]


In [14]:
n_array = np.array([[50, 29], [30, 44]])
det = np.linalg.det(n_array)
print(int(det))

1330


In [15]:
np.linalg.matrix_rank(n_array)

2

In [16]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


In [17]:
gfg = np.matrix('[6, 2; 3, 4]')
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [18]:
trans = gfg.transpose()
    
print(trans)

[[6 3]
 [2 4]]


In [19]:
tracem = gfg.trace()
    
print(tracem)

[[10]]
